# Generated by Django 4.0.5 on 2022-06-27 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curdapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsdata',
            old_name='institue',
            new_name='institute',
        ),
    ]
