# Generated by Django 4.0.4 on 2023-10-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curdapp', '0002_rename_institue_studentsdata_institute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employeedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('Emailid', models.CharField(max_length=50)),
                ('Mobile', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Studentsdata',
        ),
    ]
