# Generated by Django 4.0.4 on 2023-10-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curdapp', '0003_employeedata_delete_studentsdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedata',
            name='Emailid',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='Mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
